# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chargified}
  s.version = "0.0.1.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Smestad"]
  s.date = %q{2010-07-06}
  s.email = %q{justin.smestad@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "chargify.gemspec",
     "lib/chargified.rb",
     "lib/chargify/base.rb",
     "lib/chargify/client.rb",
     "lib/chargify/config.rb",
     "lib/chargify/customer.rb",
     "lib/chargify/extensions.rb",
     "lib/chargify/parser.rb",
     "lib/chargify/product.rb",
     "lib/chargify/proxy.rb",
     "lib/chargify/subscription.rb",
     "spec/fixtures/stale_fish.yml",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jsmestad/chargify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper for the Chargify XML API}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.5.1"])
      s.add_runtime_dependency(%q<happymapper>, [">= 0.2.4"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.1"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.5.1"])
      s.add_dependency(%q<happymapper>, [">= 0.2.4"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.1"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.5.1"])
    s.add_dependency(%q<happymapper>, [">= 0.2.4"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.1"])
  end
end

